# Generated by Django 3.2.5 on 2021-07-17 00:46

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1020)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to=products.models.upload_image_product)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
